# This is a basic workflow to generate build on latest master
name: "pre-release"

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - "master"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"
    
    steps:
      # ...
      - name: "Generate App Build"
        run: |
          echo "Started generating build."
      

      - uses: actions/checkout@v2
        with:
          ref: master
          path: uploader
      
      
      - name: "Generate App Build"
        run: |
          cd uploader
          rm -rf .github
          cd ..
          find uploader -type f -exec chmod 644 '{}' \;
          find uploader -type d -exec chmod 755 '{}' \;
          tar -czf uploader.tgz uploader
          cd ..
          
      - uses: actions/upload-artifact@v2
        with:
          name: "App Build"
          path: |
            uploader.tgz
          

      - name: "Python Installation"
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64'

# Ref - https://dev.splunk.com/enterprise/docs/developapps/testvalidate/appinspect/splunkappinspectclitool/installappinspect/installappinspectonlinux
      - name: "Install App-Inspect"
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-dev libxslt-dev lib32z1-dev python-lxml
          sudo apt-get install libmagic-dev
          pip install https://download.splunk.com/misc/appinspect/splunk-appinspect-latest.tar.gz
 

      - name: "Running App-Inspect"
        run: |
          mkdir test_results || true
          splunk-appinspect inspect --mode test --data-format junitxml --output-file test_results/app-appinspect-mode-test.xml uploader.tgz
      
      - name: "Running Cloud-Inspect"
        run: |
          splunk-appinspect inspect --mode precert --included-tags cloud --data-format junitxml --output-file test_results/app-appinspect-mode-cloud.xml uploader.tgz
      
      - uses: actions/upload-artifact@v2
        with:
          name: "app_inspect_reports"
          path: |
            test_results

      - name: "Inspect and Cloud Vetting Check"
        run: |
          if grep failures=\"[1-9] test_results/app-appinspect-mode-test.xml; then exit 1; else exit 0; fi
          if grep failures=\"[1-9] test_results/app-appinspect-mode-cloud.xml; then exit 1; else exit 0; fi
